import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";

// ✅ Mantine 必须加上这句样式引入
import '@mantine/core/styles.layer.css';
import '@mantine/notifications/styles.css';
import '@mantine/carousel/styles.css';

// Mantine Provider + createTheme
import { BackgroundImage, createTheme, MantineProvider } from '@mantine/core';
import { Notifications } from '@mantine/notifications';
// import Navbar from "@/components/Navbar";

// 导入路由重定向组件
import RouteRedirect from "@/components/RouteRedirect";
// 导入登录过期弹窗包装器
import SessionExpiredModalWrapper from "@/components/SessionExpiredModalWrapper";
// 导入错误边界组件
import ErrorBoundary from "@/components/ErrorBoundary";
import ApiErrorBoundary from "@/components/ApiErrorBoundary";
import NetworkErrorBoundary from "@/components/NetworkErrorBoundary";
import AuthErrorBoundary from "@/components/AuthErrorBoundary";

// Mantine 自定义主题（你可以按需扩展）
const theme = createTheme({
  fontFamily: "var(--font-geist-sans)",
  headings: { fontFamily: "var(--font-geist-mono)" },
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bizplus Design",
  description: "Generated by create next app",
};

export const viewport = {
  width: 'device-width',
  initialScale: 1.0,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <MantineProvider theme={theme}
          defaultColorScheme="auto"  // "light" - "dark"
          withCssVariables={true}
        >
          {/* 固定的背景层 */}
          <div 
            style={{
              position: 'fixed',
              top: 0,
              left: 0,
              width: '100vw',
              height: '100vh',
              backgroundImage: 'url(/bg.jpg)',
              backgroundSize: 'cover',
              backgroundPosition: 'center',
              backgroundRepeat: 'no-repeat',
              zIndex: -2,
            }}
          />
          
          {/* 固定的毛玻璃遮罩 */}
          <div
            style={{
              position: "fixed",
              inset: 0,
              zIndex: -1,
              background: "rgba(255,255,255,0.2)",
              backdropFilter: "blur(6px)",
              WebkitBackdropFilter: "blur(6px)",
              pointerEvents: "none",
            }}
          />
          
          {/* 内容区域 */}
          <div style={{ position: "relative", zIndex: 1, minHeight: "100vh" }}>
            <Notifications position="top-right" autoClose={3000} limit={3} />
            <ErrorBoundary>
              <NetworkErrorBoundary>
                <AuthErrorBoundary>
                  <ApiErrorBoundary>
                    <RouteRedirect>
                      <div className="flex flex-col min-h-screen">
                        {/* <Navbar /> */}
                        <main className="flex-1 px-6 py-8">
                          {children}
                        </main>
                      </div>
                    </RouteRedirect>
                  </ApiErrorBoundary>
                </AuthErrorBoundary>
              </NetworkErrorBoundary>
            </ErrorBoundary>
            {/* 登录过期弹窗包装器 - 全局组件 */}
            <SessionExpiredModalWrapper />
          </div>
        </MantineProvider>
      </body>
    </html>
  );
}
